### ISSUE TITLE
password

### ISSUE THREAD

**Issue by drmarwat** [Michael-F-Bryan/dotfiles#1]
I am trying your script but it had to be stopped because at one stage it was asking for a password for michaelfbryan@gmail.com']' returned non-zero exit status 1.
since no password is provided it crashed

**Comment by Michael-F-Bryan** [comment]
Yes, that is intentional because I don't particularly want to give you my SSH keys.

You should be able to remove [the secrets section](https://github.com/Michael-F-Bryan/dotfiles/blob/3911354f4b7c4d8832a66bf117b0bdfbc7f65551/config.json#L100-L108) from `config.json` so it doesn't try to download files from my last pass vault.

**Comment by drmarwat** [comment]
Thanks for clarifying , but when I tried ( multiple attempts , tried different ways to remove this section ) I get an error related to the removal of this part . Can I manually enter here my own email address or can you upload the same file copy as a .backup copy with this part removed so that I and others can use yours dots ? 
Thanks for sharing your work with us .
